### ISSUE TITLE
Running into activation problem. 

### ISSUE THREAD

**Issue by jcklpe** [rchipka/advanced-custom-blocks#1]
I installed plugin from zip from zip file. I changed wp.hooks to wp.acf_hooks as per the instructions on the README. But I get this error code:

`Parse error: syntax error, unexpected end of file in /app/public/wp-content/plugins/wp-acf-gutenberg-master/wp-acf-gutenburg.php on line 284
`

O checked the file but I don't see what it's referring to. Line 284 is the end of the file and is blank. 

Could maybe be a jQuery compatibility issue?

**Comment by jcklpe** [comment]
BINGO. Figured it out. For some reason at the end of the file it says <? when it should be <?php

Now it's activated. I'm going to test it!

**Comment by jcklpe** [comment]
Okay so it's activated no problem but now when I try and create a new post in Gutenberg it doesn't load the new post page. It just remains blank. I deactivate the plugin and then the new post page loads again. I created a shared block (which is the same as a custom block correct?) beforehand called testblock, and I got into ACF pro, create a new field group and target it to a custom block equal to core/testblock. I've also tried core/paragraph as per the images in https://github.com/elliotcondon/acf/issues/622#issuecomment-379499471 and this also does not work.

**Comment by jcklpe** [comment]
Here's the error code from the dev tools:

`Uncaught TypeError: Cannot set property 'acf_fields' of undefined
    at post.php?post=1357&action=edit:1107
    at index.js?ver=1523132025:1
    at Te (index.js?ver=1523132024:18)
    at index.js?ver=1523132024:18
    at Array.forEach (<anonymous>)
    at Object.Dl (index.js?ver=1523132024:18)
    at Object.<anonymous> (post.php?post=1357&action=edit:2768)
    at Object.<anonymous> (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=4.9.5:2)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=4.9.5:2)
    at Object.add [as done] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=4.9.5:2)`

![image](https://user-images.githubusercontent.com/9451726/38461415-e032f26e-3a94-11e8-9f9d-7e66f2b7ce69.png)

**Comment by rchipka** [comment]
@thedonquixotic should have a fix for this soon

**Comment by jcklpe** [comment]
Excellent. Great work man! Saw your post in the other thread and your plans for this project sound awesome!

If you need any help with a logo or anything let me know :) Trying to become a better contributor to code projects but my strength still lies in design, but sometimes that's useful!

**Comment by jcklpe** [comment]
Any updates on this?

**Comment by rchipka** [comment]
Try the latest changes.

Will require installing https://github.com/rchipka/gutenberg-block-partials

**Comment by jcklpe** [comment]
Will do.

Sincerely,David Aslan French  
Jackalope.tech Design X Code: Pushing the boundaries of design, art, and code.
 jackalope.tech  
Find me on Facebook  Let's connect!  








On Tue, Apr 24, 2018 10:14 AM, Robbie Chipka notifications@github.com  wrote:
Try the latest changes.

Will require installing https://github.com/rchipka/gutenberg-block-partials

**Comment by thedonquixotic** [comment]
@rchipka Hey not to bother you but out of curiosity do you think this is still worth me trying out? I've been following the conversation in the ACF github but I'm not entirely clear on what Elliot's strategy is going to be with ACF and if it duplicates this extension's behavior or not. Thoughts?

You can also message me at david@jackalope.tech if you prefer to not muddy your issues alerts etc.
