### ISSUE TITLE
Unable to create new field group with block after reinstalling

### ISSUE THREAD

**Issue by jcklpe** [rchipka/advanced-custom-blocks#10]
I reinstalled the plugin to my local dev site in order to try and reproduce one of the bugs here and instead I found myself unable to actually complete the creation of a custom block. Instead whenever I hit publish I get this:

![image](https://user-images.githubusercontent.com/9451726/44770143-ab8f3500-ab2c-11e8-835a-5a0de60bcdb8.png)

Any other information I could provide to help with troubleshooting this?

**Comment by ATomilov** [comment]
@thedonquixotic , hi. I can't reproduce it
![image](https://user-images.githubusercontent.com/14121426/44897468-a218ef00-ad1d-11e8-9328-a092f909f352.png)

**Comment by jcklpe** [comment]
I'm going to close this as I am not using ACB on my current project right now (I decided to rebuild my portfolio as a streamlined Gutenberg only vanilla WP theme). But I'll probably be experimenting with this thing again soon when I move back to my personal blog project. I'll make a new issue at that time.
