### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by jmml97** [rchipka/advanced-custom-blocks#13]
When trying to activate the plugin after being uploaded I get this error:
`Parse error: syntax error, unexpected end of file in C:\xampp\htdocs\dgewp\wp-content\plugins\advanced-custom-blocks-master\advanced-custom-blocks.php on line 372`

It can be solved by changing `<?` on line 370 to `<?php`

**Comment by ATomilov** [comment]
@jmml97  hi. In pull requests have one of same solution. But on local temporary solutions it's activate support short php tag.

**Comment by jcklpe** [comment]
I also made a pull request for this months ago but hasn't been accepted :( https://github.com/rchipka/advanced-custom-blocks/pull/2/commits/a7f9600b89849cecc82704acffd97b2bc7316c5c

Though now it shouldn't be because the file name has changed!
