### ISSUE TITLE
Maybe a dumb question but having some issue getting a custom block come up in the menu

### ISSUE THREAD

**Issue by jcklpe** [rchipka/advanced-custom-blocks#4]
I have a feeling that I'm missing something super simple and straightforward but I'm having a bit of trouble so here's the issue. 

Downloaded the zipped repos for Advanced Custom Blocks and the master of Gutenberg Block Partials. Installed and activated both of them as plugins using the upload plugin menu. 

When I opened a new post it very briefly flashed an error message. I took a picture but unfortunately since taking it it seems my auto file cleaner bot has deleted it. 

Anyway it said something to the extent of that it couldn't find a blocks folder in my theme folder. So I created one, and now it doesn't give me an error message. BUT it also still isn't working. I create a field group in ACF just like the pictures posted in the ACF github discussion thread and it results in nada. 

![image](https://user-images.githubusercontent.com/9451726/44683931-4a247480-aa0d-11e8-97b7-3bff6e09e2e0.png)

![image](https://user-images.githubusercontent.com/9451726/44683980-6fb17e00-aa0d-11e8-8d66-01efd413c3f6.png)

![image](https://user-images.githubusercontent.com/9451726/44684008-81932100-aa0d-11e8-948f-216bd46d8a08.png)

I have a feeling I'm missing something here really basic. The main thing is that, if I think about it, it seems I should be putting something in that blocks folder that I had to create right? Was I supposed to install the gutenberg partials in my theme folder? Or maybe was I supposed to use them to write my own php template partial for the block? In the thread you said that it didn't need to write any code but it seems like I would need to, to some extent, to define how the fields would be put onto the page right?

**Comment by rchipka** [comment]
Note Gutenberg Block Partials is no longer used and might even be incompatible

**Comment by jcklpe** [comment]
I'll try uninstalling it then. What else should I do to help it log the new block type etc?

**Comment by rchipka** [comment]
[Field groups](https://github.com/rchipka/advanced-custom-blocks/blob/master/advanced-custom-blocks.php#L225) and [registered blocks](https://github.com/rchipka/advanced-custom-blocks/blob/master/advanced-custom-blocks.php#L286) will be logged to console

**Comment by rchipka** [comment]
Perhaps try publishing the post and editing in case it's a location matching issue

**Comment by rchipka** [comment]
Also, what version of Gutenberg? I tested with the latest release.

**Comment by jcklpe** [comment]
@rchipka I typed one of those console commands in the console and I got this:

```
 console.log('Register block', slug, group);
SyntaxError: unexpected token: identifier
```

Also I have the latest version of Gutenberg installed. 

I'll try publishing the post and then editing it. I also posted pictures showing the settings I put for the field groups. Maybe I set them incorrectly?

**Comment by rchipka** [comment]
Field Group settings look fine. Try removing Post Type location rule.

**Comment by jcklpe** [comment]
Hey just tried publishing and then editing and it has appeared. Not sure what that means. I also tried making a new post afterwards and again it didn't appear in the widget section. I'll try removing the post type location rule though. 

Also when I put something in the field and publishing the changes I don't see the new field information on the page. If my memory serves (It's been a couple of months since I've used WP), I have to call the content of the advanced field inside of the template in order for it to appear on the page. But in the case of something that has been put up as a block, and therefore should be inside the Content block? How would I do that?

My main purpose here is to make a new H2 block Due to the way my visual design is structured H2 headers are built like this: `<span class="header-background"> <h2> Title Here </h2> </span>`. Before Gutenberg I would just use a custom Inline Style in TinyMCE to do that, and now I've had to use a raw HTML block in which I just write out the raw HTML. But I'd much prefer a custom block etc, and this seems like the way it should be done, but then... I'm uncertain about where I'm supposed to write the php template file for the field values that get transferred on to the frontend of things. Both in the sense that I'm not clear on *how* the ACF gets distinguished in the post template when it's called by the Content block BUT ALSO  how the individual block template structure gets defined (as in where would I write out the `<span><h2> $custom_field_slug_here </h2></span>`) etc?

Thank you for any help you can provide, you've been very generous with your time.

**Comment by jcklpe** [comment]
Okay cool, yes, I can confirm removing the location rule did the trick. I'm going to fiddle around with the publishing etc process and see if I can figure out for myself how the ACF stuff gets tranferred to the page PHP etc or whatever in the mean time.

**Comment by rchipka** [comment]
Gutenberg block are in the post_content so doing `the_content()` will cause any server side renders to happen. The `acf/render-block` hooks are called when the server side render is triggered for your block.

**Comment by jcklpe** [comment]
Hmmm So I'm successfully seeing my custom gutenberg block, but I'm not seeing any indication of it on the frontend? 

Do I need to change the ACF hooks? On the Readme page it says this is no longer needed, but maybe I'm missing something or misunderstanding.

**Comment by rchipka** [comment]
Readme is outdated. Refer to the post on the ACF Gutenberg issue.

**Comment by jcklpe** [comment]
Oh rad now I see. 

Does this: 
```
<?php
add_filter('acf/render_block/name=testimonial', function ($output, $attributes) {
  ob_start();
  ?>
  <div class="testimonial">
    <img src="<? the_field('avatar'); ?>" />
    <h3><? the_field('author'); ?></h3>
    <span><? the_field('testimonial'); ?></span>
  </div>
  <?
  return ob_get_clean();
}, 10, 2);
``` 
need to go in a template php file in the template/blocks folder? So in this case I would create a file called "testimonial2.php" with the above quoted php/html snippet?

**Comment by rchipka** [comment]
in functions.php

**Comment by jcklpe** [comment]
Ah hah, yes that makes sense, since it's a filter (sorry still learning WP dev stuff). Well it works now! Thanks man!

Though now I'm having this problem: 
![image](https://user-images.githubusercontent.com/9451726/44690319-fff8be80-aa1f-11e8-8d4f-18c29d49f613.png)


which makes this:

![image](https://user-images.githubusercontent.com/9451726/44690345-13a42500-aa20-11e8-89b0-710197828040.png)

Which sounds similar to this issue: https://github.com/rchipka/advanced-custom-blocks/issues/3

**Comment by jcklpe** [comment]
Closing this issue as solved and migrating my pictures over to the other ticket which covers this issue more narrowly
