### ISSUE TITLE
Multiple "Expand details" links in upload media form

### ISSUE THREAD

**Issue by ATomilov** [rchipka/advanced-custom-blocks#5]
Find some another bug ) 
![image](https://user-images.githubusercontent.com/14121426/44706986-26bd0080-aac5-11e8-8e1a-75662fb216a4.png)

**Comment by rchipka** [comment]
@thedonquixotic Can you reproduce this with your local setup?

**Comment by ATomilov** [comment]
@rchipka hi. Maybe it's cache or something like this? I found a bit of code where this link created in original acf plugin, but I don't sure what it's right place to looking for reasons of that bug.

**Comment by ATomilov** [comment]
@rchipka hi) I understand what actions make this bug. If you created custom block with image or gallery field (without repeater as a parent) and duplicate or create new blocks same type you get +3 links "Expand details"  every time (but if you clone block in first time you get +2 links).

**Comment by ATomilov** [comment]
@rchipka P.S. I found in acf-input.js what in initialization moment (maybe initialization fields group) happened append expand links but it happened without checking if links' block is exist. I can fix it in my {custom_name_file}.js in my theme, but when media upload popup is appears we see remove this link process. Duration <1 sec. but anyway it's not good solution to use it on production:-)

**Comment by rchipka** [comment]
My initial thought is that it could be related to using `acf.do_action('ready')` [after each block render](https://github.com/rchipka/advanced-custom-blocks/blob/master/advanced-custom-blocks.php#L322).

Do we know if the issue exists when adding multiple unique media upload fields (i.e. 2+ fields that aren't duplicated in the Gutenberg editor)?

**Comment by rchipka** [comment]
Fixed in latest version
