### ISSUE TITLE
Update Readme instructions with screenshots and latest hook implementation

### ISSUE THREAD

**Issue by rchipka** [rchipka/advanced-custom-blocks#6]
@ATomilov @thedonquixotic If either of you have time to contribute, this would be greatly appreciated.

This should be straightforward since you've both implemented working solutions.

Pull needed info from the [original ACF post](https://github.com/elliotcondon/acf/issues/622).

In the mean time I'll work on closing out #3

**Comment by jcklpe** [comment]
@rchipka  I would love to help, though like I mentioned I'm still very early in my designer turned developer journey. I'll help where I can though. A good place to start would be ReadMe stuff, so I'll take this issue. Can I assign it to myself? Or should I just link it in my pull request? Sorry, very new to these processes!

**Comment by rchipka** [comment]
@thedonquixotic Just fork the repo and make a pull request and I'll merge it in when you're ready.

**Comment by rchipka** [comment]
@thedonquixotic Note: this can all be done directly on github.com if you're unfamiliar with other tools

**Comment by ATomilov** [comment]
@rchipka, thanks for your suggestion, I'll see what I can do)

**Comment by jcklpe** [comment]
Yeah working on it now :)

**Comment by jcklpe** [comment]
Also putting together a little logo for the project. Making the readme look real nice. We'll need to lock down the name though, as per https://github.com/rchipka/advanced-custom-blocks/issues/7

**Comment by jcklpe** [comment]
This issue can probably be closed against https://github.com/rchipka/advanced-custom-blocks/pull/9
