### ISSUE TITLE
Rename Plugin (someone took it) and publish to Wordpress

### ISSUE THREAD

**Issue by rchipka** [rchipka/advanced-custom-blocks#7]
Gotta publish this eventually.

Should probably clarify differences in philosophy and implementation for this project vs the soon-to-be ACF core version.

Also accepting name suggestions below.

**Comment by jcklpe** [comment]
Hmmm yes, that is a problem. Advanced Custom Blocks seems more fitting for you than the people in the wp repo since they don't actually use ACF. 

What are the main functional differences between this project and the soon to be public ACF version etc?

**Comment by rchipka** [comment]
Ideally this plugin is closely related in functionality to core ACF with the main intentions being:

### Added flexibility/extensiblity 

Adding more options (like custom block icon, field group location, pre-render/content-caching) as well as the ability to inject or include fields in an existing block and other such things that might be considered too unstable to go into ACF core product.

### Added ease of use

Adding abstractions, like easy block templates (`block/block-name.php`) as well as an easier block registration mechanism.

---

Ideally this project serves as inspiration for ACF's Gutenberg integration and is compatible with whatever ACF releases in the near future.

Lastly, this project should be deprecated once ACF adequately addresses every concern implemented by this project.

**Comment by rchipka** [comment]
In other words, this project should be an open-source, agile working ground for "experimental" features related to the integration between ACF and Gutenberg.

The feature set this project comes to aquire will essentially determine whether it's deprecated or whether it continues on as a some sort of niche/advanced feature add-on.

**Comment by jcklpe** [comment]
How about "Agile Custom Blocks"

**Comment by rheinardkorf** [comment]
@rchipka I've reached out to you in an email. Don't be too hasty on renaming.

**Comment by jcklpe** [comment]
This issue seems worth closing per new info from the other project.
