### ISSUE TITLE
Discussion: Action/Filter API

### ISSUE THREAD

**Issue by rchipka** [rchipka/advanced-custom-blocks#8]
## Why a Filter and not an Action currently?

The reason I chose a filter is for more flexibility when overriding, replacing, or wrapping specific block types.

I think an action API would probably be easier though, so..

## Rename filters

We should rename the filter API to use the name `acf/block_content` instead

## Action API

We should add action for `acf/render_block`, which will catch the output using output buffering.

This captured output should then be run through the `acf/block_content` filters.

This way, implementations that aren't concerned with replacing content don't have to worry about implementing using a filter and therefore also using `ob_start()`, etc. each time.

**Comment by rchipka** [comment]
We've switched from filters to actions.

```php
<?php

// before_render_block
do_action('acf/before_render_block', $attributes);
do_action('acf/before_render_block/name=' . $attributes['block_name'], $attributes);

// render_block
do_action('acf/render_block', $attributes);
do_action('acf/render_block/name=' . $attributes['block_name'], $attributes);

// after_render_block
do_action('acf/after_render_block', $attributes);
do_action('acf/after_render_block/name=' . $attributes['block_name'], $attributes);
```

@jcklpe @ATomilov Please note that your current implementation will need to be updated to use one of these actions instead.

We should also update the readme.

**Comment by jcklpe** [comment]
Hey did you make the changes or should I? I don't have ACB installed right now so it's been out of my brain loop for a bit.

**Comment by rchipka** [comment]
@jcklpe I updated the readme, thanks!
